# apps/api-gateway/Dockerfile.dev

# Etapa de desarrollo
FROM node:20-alpine

# Establecer el directorio de trabajo en la aplicación
WORKDIR /usr/src/app # Usar una ruta más estándar como /usr/src/app o /opt/app

# Copiar primero package.json y package-lock.json (o yarn.lock, pnpm-lock.yaml)
# Esto aprovecha el cache de Docker si no cambian las dependencias
COPY package*.json ./

# Instalar todas las dependencias (incluyendo devDependencies para desarrollo)
RUN npm install

# Copiar el resto del código del monorepo.
# Es importante tener un .dockerignore bien configurado en la raíz
# para no copiar node_modules innecesarios o carpetas dist de otros servicios.
COPY . .

# Puerto que expone el API Gateway dentro del contenedor
# Este es el puerto que la aplicación NestJS escucha (definido por GATEWAY_PORT o el default)
EXPOSE ${GATEWAY_PORT:-8080}

# Comando para iniciar el API Gateway en modo desarrollo con hot-reload
# Este comando se ejecuta desde la raíz del monorepo (WORKDIR /usr/src/app)
# y asume que 'api-gateway' es el nombre del proyecto en nest-cli.json
CMD ["npm", "run", "start:dev:api-gateway"]